spring.application.name=demo_ss11

# kết nối đến CSDL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_ss11
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#logging
logging.file.name=logs/runtime_project.log
logging.file.path=logs
logging.level.root=INFO
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} - %level - %logger - %msg%n
logging.pattern.level=%5p
# đặc biệt khi lưu file phải có cấu hình về rollingpolicy quản lý vê vòng loggin
logging.logback.rollingpolicy.max-file-size=10MB
# --> 10MB --> file .gz
logging.logback.rollingpolicy.max-history=7
# khi mà muốn hiển thị định dạng dưới dạng JSON thì nên cần
logging.structured.format.console=ecs
logging.structured.format.file=logstash