spring.application.name=btth_ss11

# kết nối đến CSDL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/btth_ss11
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# logging
logging.file.name=logs/atm-service.log
logging.file.path=logs
logging.level.root=INFO
# [Thời gian] - [Mức độ Log 5 ký tự] - [Tên luồng] - [Tên Class] - [Nội dung log]
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss:SSS} - %level - %thread - %logger - %msg%n
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss:SSS} - %level - %thread - %logger - %msg%n
logging.pattern.level=%5p
logging.logback.rollingpolicy.max-file-size=2MB
logging.logback.rollingpolicy.max-history=7