spring.application.name=ss08

# kết nối đến CSDL
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5432/demo_ss08
spring.datasource.username=postgres
spring.datasource.password=123456

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=50MB

cloudinary.cloud-name=my-storage-bucket
cloudinary.api-key=152922968893657
cloudinary.api-secret=zEf-4lyxxrPqJc1TNe5pBOwL3s4
